version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: api
    container_name: book-review-app
    ports:
      - '4000:4000'
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/myDB
    networks:
      - backend

  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

volumes:
  mongo-data:

networks:
  backend:
    driver: bridge
