name: Build & Push Docker Images

on:
  workflow_dispatch:
    inputs:
      app:
        description: "App name to build"
        required: true
        type: string
      version:
        description: "Version to tag the Docker image"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image with APP_NAME arg
        run: |
          APP_NAME=${{ github.event.inputs.app }}
          VERSION=${{ github.event.inputs.version }}
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/$APP_NAME
          docker build \
            --build-arg APP_NAME=$APP_NAME \
            -t $IMAGE_NAME:latest \
            -t $IMAGE_NAME:$VERSION .

      - name: Push Docker images
        run: |
          APP_NAME=${{ github.event.inputs.app }}
          VERSION=${{ github.event.inputs.version }}
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/$APP_NAME
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$VERSION
